# AUTOGENERATED! DO NOT EDIT! File to edit: 01_lfq_manager.ipynb (unless otherwise specified).

__all__ = ['run_lfq', 'save_protein_df']

# Cell
import directlfq.normalization as lfqnorm
import directlfq.protein_intensity_estimation as lfqprot_estimation
import directlfq.utils as lfqutils


def run_lfq(input_file = None, input_type_to_use = None):
    input_file = lfqutils.reformat_and_save_input_file(input_file, input_type_to_use = input_type_to_use)
    input_df = lfqutils.import_data(input_file=input_file)
    input_df_normed = lfqnorm.normalize_samples(input_df)
    protein_df = lfqprot_estimation.estimate_protein_intensities(input_df_normed)
    save_protein_df(protein_df)

def save_protein_df(protein_df, input_file):
    protein_df.to_csv(f"{input_file}.protein_intensities.tsv", sep = "\t")

