on:
  #  push:
  #    branches: [ master, Development ]
  #  pull_request:
  #    branches: [ master, Development ]
   workflow_dispatch:

name: All tests based on default installation

jobs:
  loose_installation:
    name: Test loose pip installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
      - name: Conda info
        shell: bash -le {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -le {0}
        run: |
          cd misc
          ./pip_install.sh loose,tests
      - name: Unittests
        shell: bash -le {0}
        run: |
          cd tests
          . ./run_tests.sh
