import directlfq.lfq_manager as lfq_manager

lfq_manager.run_lfq(input_file = "/Users/vincenthbrennsteiner/Documents/mann_labs/_git_repositories/projects/collaborations/DirectLFQ/notebooks/data/pars_05_ALL_MBR_with_speclib_ALL_COHORTS_20250222_SAMPLE_3_FILES_COPY_fragment_quantities.parquet")
