name: branch-checks
on:
  pull_request

jobs:
  pre-commit:
    name: Run all pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: pip install pre-commit==4.3.0
    - uses: pre-commit/action@v3.0.1
